language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  - sudo apt-get update
  - sudo apt-get install libssh2-1-dev libssh2-php
  - echo '' | pecl install -f ssh2
  - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - php -m | grep ssh2
  - "travis_wait 30 sleep 1800 &"
  - composer install

script:
  - vendor/bin/phpunit
